services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    configs:
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/datasource.yml
      - source: grafana_dashboard_config
        target: /etc/grafana/provisioning/dashboards/dashboard.yml
      - source: prometheus_dashboard
        target: /var/lib/grafana/dashboards/prometheus.json
    volumes:
      - grafana-storage:/var/lib/grafana

configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'mlflow'
          static_configs:
            - targets: ['host.docker.internal:5000']
            
  grafana_datasource:
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true
          editable: true
          
  grafana_dashboard_config:
    content: |
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          options:
            path: /var/lib/grafana/dashboards
            
  prometheus_dashboard:
    content: |
      {
        "dashboard": {
          "title": "Prometheus Overview",
          "panels": [
            {
              "title": "Up Targets",
              "type": "stat",
              "targets": [
                {
                  "expr": "up",
                  "refId": "A"
                }
              ]
            }
          ]
        }
      }

volumes:
  grafana-storage: