services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    configs:
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/datasource.yml
      - source: grafana_dashboard_provider
        target: /etc/grafana/provisioning/dashboards/dashboard.yml
      - source: mlnet_dashboard
        target: /var/lib/grafana/dashboards/mlnet-dashboard.json
    volumes:
      - grafana-storage:/var/lib/grafana


configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'mlflow'
          static_configs:
            - targets: ['host.docker.internal:5000']
            
  grafana_datasource:
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true
          editable: true
          
  grafana_dashboard_provider:
    content: |
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards
            
  mlnet_dashboard:
    content: |
      {
        "id": null,
        "title": "ML.NET AutoML Monitoring Dashboard",
        "tags": ["machine-learning", "automl", "dotnet"],
        "style": "dark",
        "timezone": "",
        "panels": [
          {
            "id": 1,
            "title": "Model Performance Metrics",
            "type": "row",
            "gridPos": {"h": 1, "w": 24, "x": 0, "y": 0},
            "collapsed": false
          },
          {
            "id": 2,
            "title": "R-Squared Score",
            "type": "stat",
            "gridPos": {"h": 8, "w": 6, "x": 0, "y": 1},
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "thresholds"},
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {"color": "red", "value": 0},
                    {"color": "yellow", "value": 0.5},
                    {"color": "green", "value": 0.8}
                  ]
                },
                "unit": "percentunit",
                "min": 0,
                "max": 1
              }
            },
            "options": {
              "reduceOptions": {
                "values": false,
                "calcs": ["lastNotNull"],
                "fields": ""
              },
              "orientation": "auto",
              "textMode": "auto",
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto"
            },
            "targets": [{"expr": "model_r2", "refId": "A"}]
          },
          {
            "id": 3,
            "title": "RMSE",
            "type": "stat",
            "gridPos": {"h": 8, "w": 6, "x": 6, "y": 1},
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "thresholds"},
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {"color": "green", "value": 0},
                    {"color": "yellow", "value": 0.5},
                    {"color": "red", "value": 1.0}
                  ]
                },
                "unit": "short",
                "decimals": 4
              }
            },
            "options": {
              "reduceOptions": {
                "values": false,
                "calcs": ["lastNotNull"],
                "fields": ""
              },
              "orientation": "auto",
              "textMode": "auto",
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto"
            },
            "targets": [{"expr": "model_rmse", "refId": "A"}]
          },
          {
            "id": 4,
            "title": "Model Metrics Over Time",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 1},
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "palette-classic"},
                "custom": {
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "drawStyle": "line",
                  "fillOpacity": 10,
                  "gradientMode": "none",
                  "hideFrom": {"legend": false, "tooltip": false, "vis": false},
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {"type": "linear"},
                  "showPoints": "never",
                  "spanNulls": false,
                  "stacking": {"group": "A", "mode": "none"},
                  "thresholdsStyle": {"mode": "off"}
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [{"color": "green", "value": null}]
                },
                "unit": "short"
              },
              "overrides": [
                {
                  "matcher": {"id": "byName", "options": "R-Squared"},
                  "properties": [
                    {"id": "unit", "value": "percentunit"},
                    {"id": "max", "value": 1},
                    {"id": "min", "value": 0}
                  ]
                }
              ]
            },
            "options": {
              "legend": {"calcs": [], "displayMode": "list", "placement": "bottom"},
              "tooltip": {"mode": "single"}
            },
            "targets": [
              {"expr": "model_r2", "legendFormat": "R-Squared", "refId": "A"},
              {"expr": "model_rmse", "legendFormat": "RMSE", "refId": "B"}
            ]
          },
          {
            "id": 5,
            "title": "Memory Usage",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 10},
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "palette-classic"},
                "custom": {
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "drawStyle": "line",
                  "fillOpacity": 10,
                  "gradientMode": "none",
                  "hideFrom": {"legend": false, "tooltip": false, "vis": false},
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {"type": "linear"},
                  "showPoints": "never",
                  "spanNulls": false,
                  "stacking": {"group": "A", "mode": "none"},
                  "thresholdsStyle": {"mode": "off"}
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [{"color": "green", "value": null}]
                },
                "unit": "bytes"
              }
            },
            "options": {
              "legend": {"calcs": [], "displayMode": "list", "placement": "bottom"},
              "tooltip": {"mode": "single"}
            },
            "targets": [
              {"expr": "dotnet_total_memory_bytes", "legendFormat": ".NET Total Memory", "refId": "A"},
              {"expr": "process_working_set_bytes", "legendFormat": "Working Set", "refId": "B"},
              {"expr": "process_private_memory_bytes", "legendFormat": "Private Memory", "refId": "C"}
            ]
          },
          {
            "id": 6,
            "title": "GC Collections Rate",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 10},
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "palette-classic"},
                "custom": {
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "drawStyle": "line",
                  "fillOpacity": 10,
                  "gradientMode": "none",
                  "hideFrom": {"legend": false, "tooltip": false, "vis": false},
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {"type": "linear"},
                  "showPoints": "never",
                  "spanNulls": false,
                  "stacking": {"group": "A", "mode": "none"},
                  "thresholdsStyle": {"mode": "off"}
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [{"color": "green", "value": null}]
                },
                "unit": "ops"
              }
            },
            "options": {
              "legend": {"calcs": [], "displayMode": "list", "placement": "bottom"},
              "tooltip": {"mode": "single"}
            },
            "targets": [
              {"expr": "rate(dotnet_collection_count_total[5m])", "legendFormat": "Gen {{generation}} Collections/sec", "refId": "A"}
            ]
          }
        ],
        "time": {"from": "now-1h", "to": "now"},
        "timepicker": {},
        "timezone": "",
        "refresh": "5s",
        "schemaVersion": 27,
        "version": 0,
        "links": []
      }

volumes:
  grafana-storage: